import type { Metadata } from 'next'
import { Inter as FontSans } from "next/font/google"
import './globals.css'

import Nav from '@/components/MyComponent/Nav/page'
import Footer from '@/components/MyComponent/Footer/page'

import { cn } from '@/lib/utils'

const inter = FontSans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
      className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable,
        // "max-container",
        "bg-primary"

      )}
    >

      <body className={inter.className}>
        <Nav />

          {children}
        
      </body>
      <Footer />
    </html>
  )
}
